services:
  postgres:
    container_name: login_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: login_db
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
#volumes:
#  postgres_data:
